### ISSUE TITLE
basis

### ISSUE THREAD

**Issue by 13yong** [Xiaoxun-Gong/HPRO#1]
Hello xiaoxun
I am a new user about this. I have a question. How can I get the aobasis for my structure like "examples/MoS2_demo/reconstruction/aobasis".
Thank you !

**Comment by Xiaoxun-Gong** [comment]
Thanks for bringing this up. I also realized that I did not include instructions on how to generate the atomic orbital basis set in the demo. Now, in the updated demo, you can find the procedures for generating basis sets.

**Comment by 13yong** [comment]
> Thanks for bringing this up. I also realized that I did not include instructions on how to generate the atomic orbital basis set in the demo. Now, in the updated demo, you can find the procedures for generating basis sets.

Thank you for your reply!
Now, I can run the demo easily.
But when I use my own Sm element, SIESTA gives me an error as follows:
[SIESTA.zip](https://github.com/user-attachments/files/17879348/SIESTA.zip)
If you have the time to take a look at it, that would be great, or some advice based on your experience would be great appreciated !
I'm looking for your reply. Best wishes.

**Comment by Xiaoxun-Gong** [comment]
I found this [discussion](https://www.mail-archive.com/siesta-l@uam.es/msg11424.html) on the siesta forum. Looks like they have exactly the same issue as yours. Hope this can solve your problem.

**Comment by 13yong** [comment]
Yeah, thank you very much. Now it work.

**Comment by 13yong** [comment]
#### Sorry Xiaoxun, now I have anotrher issue about HPRO. When I run "calc.py", the errors are as floow:
Traceback (most recent call last):
  File "/HPRO/utils.py", line 191, in g
    return f(*args, **kwargs)
  File "/HPRO/utils.py", line 274, in g
    ret = f(*args, **kwargs)
  File "/HPRO/kernel.py", line 141, in __init__
    vlocr = read_vloc(vscdir, hrdata_interface.split('-')[1]) # bgw or deephr
  File "/HPRO/hrdata.py", line 31, in read_vloc
    vscg_full[g_g_full[:, 0], g_g_full[:, 1], g_g_full[:, 2]] = vscread.vscg
ValueError: shape mismatch: value array of shape (2,276257) could not be broadcast to indexing result of shape (276257,)

#### And then I check the dim using, 
print("Indexing results shape:", g_g_full[:, 0].shape)
print("Number of target indexes", len(g_g_full))
print("Target number of assignments", vscread.vscg.shape[1])
#### the results are:
(276257, 3)
(120, 60, 100)
(2, 276257)

#### So I replace the 
_"vscg_full[g_g_full[:, 0], g_g_full[:, 1], g_g_full[:, 2]] = vscread.vscg"_ by 
**"vscg_full[g_g_full[:, 0], g_g_full[:, 1], g_g_full[:, 2]] = vscread.vscg[0, :]"**
#### And then it works. 
### But I dont't know this change is right. My system is spin=2, does it have anything to do with that? If you need more details, let me know.
Thank you!

**Comment by Xiaoxun-Gong** [comment]
Currently HPRO has no support for spinful DFT calculations.

**Comment by 13yong** [comment]
Yeah, I get it. I'll keep you posted.
